[package]
name = "TetrisAIrs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
num = "*"
rand = "0.8.5"
crossterm_cursor = "0.4.0"
console = "0.15.0"
libc = "0.2.126"
numtoa = "0.1.0"
redox_syscall = "0.2.13"
redox_termios = "0.1.2"
termion = "1.5.3"
